"""
Population-level coverage tables from the trend-analytics responses saved by
script 26 (data/raw/trend_<source>.json). Makes no API calls.

The trend endpoint returns one row per source, country (`location_code`) and
month. Check against our POST /jobs counts (script 26 run, 2026-10-08): the two
agree exactly for every source and year except that postings WITHOUT a
`location_code` are not in the trend rows (all of jobscentral and brightminds,
about a third of OJA 2024, a handful in the EURES family). So these tables are
counts of postings that have a country code.

Writes:
  data/raw/trend_monthly.csv      source, month, location_code, count
  docs/coverage_population.md     1. source x year   2. first/last month, countries
                                  3. country x year, non-OJA   4. monthly matrix, main sources

Usage, from the repo root:
    python -m diagnostics.27_coverage_from_trend
"""

import csv
import json
import re
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

RAW = Path("data/raw")
CSV_PATH = RAW / "trend_monthly.csv"
REPORT_PATH = Path("docs/coverage_population.md")
MAIN = ["eures", "eures-escox", "kariera.gr", "jobbland.se", "lesjeudis.com", "jobs.de", "kariera.fr"]


def rows_of(payload):
    if isinstance(payload, list):
        return payload
    if isinstance(payload, dict):
        for key in ("items", "data", "results", "rows"):
            if isinstance(payload.get(key), list):
                return payload[key]
    return []


def parse_month(value):
    m = re.match(r"^(\d{2})/(\d{4})$", str(value).strip())
    return f"{m.group(2)}-{m.group(1)}" if m else None


def load():
    data = {}
    for path in sorted(RAW.glob("trend_*.json")):
        source = path.stem[len("trend_"):]
        if source == "monthly":
            continue
        rows = []
        for r in rows_of(json.loads(path.read_text(encoding="utf-8"))):
            month = parse_month(r.get("Date"))
            freq = r.get("Freq")
            if month and isinstance(freq, (int, float)):
                rows.append((month, r.get("location_code") or "none", int(freq)))
        data[source] = rows
    return data


def main():
    data = load()
    if not data:
        print("No data/raw/trend_*.json files; run script 26 first.")
        return
    with open(CSV_PATH, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["source", "month", "location_code", "count"])
        for s, rows in data.items():
            for month, code, n in rows:
                w.writerow([s, month, code, n])

    today_month = date.today().strftime("%Y-%m")
    years = sorted({m[:4] for rows in data.values() for m, _, _ in rows})
    by_year = {s: Counter() for s in data}
    for s, rows in data.items():
        for m, _, n in rows:
            by_year[s][m[:4]] += n
    out = ["# Population-level coverage from the API trend endpoint", "",
           "Counts of postings **with a `location_code`**, by month of `upload_date`. Agrees exactly with "
           "the filtered POST /jobs counts except that postings without a country code are absent "
           "(all of `jobscentral` and `brightminds`; roughly a third of OJA in 2024). "
           "Generated by `diagnostics/27_coverage_from_trend.py` from `data/raw/trend_*.json`.", ""]

    out += ["## 1. Postings by source and year", ""]
    out.append("| Source | " + " | ".join(years) + " | Total |")
    out.append("|---|" + "---|" * (len(years) + 1))
    for s in sorted(data, key=lambda k: -sum(by_year[k].values())):
        out.append(f"| {s} | " + " | ".join(f"{by_year[s][y]:,}" if by_year[s][y] else "-" for y in years)
                   + f" | {sum(by_year[s].values()):,} |")
    non = Counter()
    for s in data:
        if s != "OJA":
            non.update(by_year[s])
    out.append("| **All except OJA** | " + " | ".join(f"{non[y]:,}" if non[y] else "-" for y in years)
               + f" | {sum(non.values()):,} |")
    out += ["", "Duplicate-pair members (`jobbland`/`jobbland.se`, `lesjeudis`/`lesjeudis.com`, "
            "`jobmedic`/`jobmedic.co.uk`, `jobbguru`/`jobbguru.se`) are listed separately here and are "
            "counted twice in the totals; see Section 13.4 of the data quality report.", ""]

    out += ["## 2. First and last month with data, and countries", "",
            "| Source | First month | Last month | Months with data | Countries (share of postings) | Postings dated after the current month |",
            "|---|---|---|---|---|---|"]
    for s in sorted(data):
        rows = data[s]
        if not rows:
            out.append(f"| {s} | - | - | 0 | none (no `location_code` on any posting) | - |")
            continue
        months = sorted({m for m, _, _ in rows})
        total = sum(n for _, _, n in rows)
        cc = Counter()
        for _, c, n in rows:
            cc[c] += n
        ctry = ", ".join(f"{c} {100 * v / total:.0f}%" for c, v in cc.most_common(5))
        future = sum(n for m, _, n in rows if m > today_month)
        out.append(f"| {s} | {months[0]} | {months[-1]} | {len(months)} | {ctry} | {future:,} |")
    out.append("")

    out += ["## 3. Country by year, all sources except OJA", ""]
    cy = defaultdict(Counter)
    for s, rows in data.items():
        if s == "OJA":
            continue
        for m, c, n in rows:
            cy[c][m[:4]] += n
    yrs = [y for y in years if any(cy[c][y] for c in cy)]
    out.append("| Country | " + " | ".join(yrs) + " | Total |")
    out.append("|---|" + "---|" * (len(yrs) + 1))
    for c in sorted(cy, key=lambda k: -sum(cy[k].values())):
        out.append(f"| {c} | " + " | ".join(f"{cy[c][y]:,}" if cy[c][y] else "-" for y in yrs)
                   + f" | {sum(cy[c].values()):,} |")
    out += ["", "Pairs listed twice in Section 1 are also counted twice here.", ""]

    out += ["## 4. Monthly postings, main sources", ""]
    present = [s for s in MAIN if s in data]
    mm = defaultdict(Counter)
    for s in present:
        for m, _, n in data[s]:
            mm[m][s] += n
    months = sorted(m for m in mm if "2024-01" <= m <= today_month)
    out.append("| Month | " + " | ".join(present) + " |")
    out.append("|---|" + "---|" * len(present))
    for m in months:
        out.append(f"| {m} | " + " | ".join(f"{mm[m][s]:,}" if mm[m][s] else "-" for s in present) + " |")
    out.append("")
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(out) + "\n", encoding="utf-8")
    print("\n".join(out))
    print(f"\nWritten to {REPORT_PATH} and {CSV_PATH}")


if __name__ == "__main__":
    main()
